spring.application.name=hackhub-Springboot
# Configurazione Database H2 (In-memory)
spring.datasource.url=jdbc:h2:mem:hackhubdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2 (per vedere il DB nel browser all'indirizzo http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra le query SQL nei log per il debug
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Mostra i messaggi di errore nelle risposte JSON
server.error.include-message=always

